version: '3'

services:
  app:
    container_name: 'app'
    restart: always
    build: ./
    ports:
      - "8000:8000"
    command: pipenv run gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
    - "80:80"
    depends_on:
      - app

