version: '3'

services:
  app:
    container_name: 'app'
    restart: always
    image: 155706891817.dkr.ecr.ap-northeast-2.amazonaws.com/flask-ecr-ecs-demo:app
    build: app
    ports:
      - "8000:8000"
    command: pipenv run gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app

  nginx:
    container_name: nginx
    restart: always
    image: 155706891817.dkr.ecr.ap-northeast-2.amazonaws.com/flask-ecr-ecs-demo:nginx
    build: nginx
    ports:
    - "80:80"
    depends_on:
      - app

