version: '3.8'

services:
 web:
  build:
   context: .
  ports:
  - 5000:5000
  volumes:
  - ./:/app
  depends_on:
   - db
  environment:
   - FLASK_ENV=development
  command: pipenv run python3 -m flask run --host=0.0.0.0

 db:
  image: mysql
  ports:
  - 3306:3306
  environment:
   - MYSQL_ROOT_USER
   - MYSQL_ROOT_PASSWORD
  volumes:
   - mysql:/var/lib/mysql
   - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config: